import cartoon1 from "../../assets/cartoon1.jpg";
import cartoon2 from "../../assets/cartoon2.jpg";
import cartoon3 from "../../assets/cartoon3.jpg";
import cartoon4 from "../../assets/cartoon4.jpg";
import cartoon5 from "../../assets/cartoon5.jpg";
import cartoon6 from "../../assets/cartoon6.jpg";
import cartoon7 from "../../assets/cartoon7.jpg";

const userdata = [
  {
    id: 1,
    profile: cartoon1,
    name: "Vishal",
    email: "vishal@gmail.com",
    gender: "Male",
    phone: "7755934563",
    status: "Unblock",
    message: "new contact",
    fullname: "kishor Ahir",
  },
  {
    id: 2,
    profile: cartoon2,
    name: "Uday",
    email: "uday@gmail.com",
    gender: "Male",
    phone: "8090457836",
    status: "Unblock",
    message: "new contact",
    fullname: "jatin Ahir",
  },
  {
    id: 3,
    profile: cartoon3,
    name: "Aj",
    email: "aj@gmail.com",
    gender: "Male",
    phone: "9999999999",
    status: "Unblock",
    message: "hello admin",
    fullname: "John Jeams",
  },
  {
    id: 4,
    profile: cartoon1,
    name: "Jani",
    email: "jani@gmail.com",
    gender: "Male",
    phone: "2222222222",
    status: "Unblock",
    message: "hiii ",
    fullname: "Yogesh sharma",
  },
  {
    id: 5,
    profile: cartoon2,
    name: "Titu",
    email: "titu@gmail.com",
    gender: "Male",
    phone: "7852647896",
    status: "Unblock",
    message: "hello !",
    fullname: "Ashish shah",
  },
  {
    id: 6,
    profile: cartoon7,
    name: "Khushi",
    email: "khushi@gmail.com",
    gender: "Female",
    phone: "6385795842",
    status: "Unblock",
    message: "hlw..",
    fullname: "shani Prajapati",
  },
  {
    id: 7,
    profile: cartoon7,
    name: "Riya",
    email: "riya@gmail.com",
    gender: "Female",
    phone: "9876543210",
    status: "Block",
    message: "Need more information.",
    fullname: "Riya Patel",
  },
  {
    id: 8,
    profile: cartoon5,
    name: "Amit",
    email: "amit@gmail.com",
    gender: "Male",
    phone: "9123456789",
    status: "Unblock",
    message: "Thank you!",
    fullname: "Amit Shah",
  },
  {
    id: 9,
    profile: cartoon7,
    name: "Neha",
    email: "neha@gmail.com",
    gender: "Female",
    phone: "9012345678",
    status: "Unblock",
    message: "Please contact me.",
    fullname: "Neha Joshi",
  },
  {
    id: 10,
    profile: cartoon1,
    name: "Rahul",
    email: "rahul@gmail.com",
    gender: "Male",
    phone: "9988776655",
    status: "Block",
    message: "Waiting for your reply.",
    fullname: "Rahul Mehta",
  },
  {
    id: 11,
    profile: cartoon7,
    name: "Priya",
    email: "priya@gmail.com",
    gender: "Female",
    phone: "8899776655",
    status: "Unblock",
    message: "Good morning!",
    fullname: "Priya Desai",
  },
];

export default userdata;
